[package]
name = "statusbar"
version = "0.1.0"
authors = ["Emanuel Aviles - Statusbar - inspiration GamozoLabs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*" 
